FROM golang:1.20 as builder
RUN apt update -yq && apt install -yq clang llvm make libpcap-dev libbpf-dev build-essential
WORKDIR /src
COPY go.* .
RUN go mod download
COPY . .
RUN make mac-build

FROM ubuntu:22.04
RUN apt-get update -yq && apt-get install -yq ca-certificates curl clang llvm make libpcap-dev libbpf-dev build-essential golang iproute2
COPY --from=builder /src/hny-ebpf-agent /bin/hny-ebpf-agent
CMD [ "/bin/hny-ebpf-agent" ]