apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
rules:
  - apiGroups: ["", "metrics.k8s.io","apps"]
    resources: ["*"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Chart.Name }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.version | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.image.version | quote }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      hostNetwork: true
      containers:
        - name: hny-network-agent
          image: "{{ .Values.image.repository }}:{{ .Values.version | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HONEYCOMB_API_KEY
              value: {{ .Values.honeycomb.apikey }}
            - name: HONEYCOMB_API_ENDPOINT
              value: {{ .Values.honeycomb.endpoint }}
            - name: HONEYCOMB_DATASET
              value: {{ .Values.honeycomb.dataset }}
            - name: HONEYCOMB_STATS_DATASET
              value: {{ .Values.honeycomb.stats_dataset }}
          securityContext:
            capabilities:
              add:
                - NET_RAW