honeycomb:
  apiKey: "bogosity" # we'll be sending to a Collector in smoke tests
  endpoint: "http://$OTEL_COLLECTOR_IP:4317"

image:
  repository: hny/network-agent
  # use local image for testing instead of helm chart default
  tag: local

extraEnvVars:
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "environment=smokey"
  - name: INCLUDE_REQUEST_URL
    value: "true"
  - name: HTTP_HEADERS
    value: "User-Agent,Traceparent,X-Custom-Header"
  - name: OTEL_EXPORTER_OTLP_INSECURE
    value: "true"
  - name: LOG_LEVEL
    value: "DEBUG"
