honeycomb:
  apiKey: "bogosity" # we'll be sending to a Collector in smoke tests
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id
  # smokey-collector-opentelemetry-collector-0 is Pod Name
  # smokey-collector-opentelemetry-collector.default.svc.cluster.local is StatefulSet Domain
  # endpoint: http://smokey-collector-opentelemetry-collector-0.smokey-collector-opentelemetry-collector.default.svc.cluster.local:4317
  # endpoint: "http://smokey-collector-opentelemetry-collector:4317"
  # setting the endpoint with the IP address works... what are we missing with the name?
  # endpoint: "http://10.244.0.6:4317"
  endpoint: "http://$OTEL_COLLECTOR_IP:4317"

image:
  repository: hny/network-agent
  # use local image for testing instead of helm chart default
  tag: local

extraEnvVars:
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "environment=smokey"
  - name: INCLUDE_REQUEST_URL
    value: "true"
  - name: HTTP_HEADERS
    value: "User-Agent,Traceparent,X-Custom-Header"
  - name: OTEL_EXPORTER_OTLP_INSECURE
    value: "true"
  - name: LOG_LEVEL
    value: "DEBUG"
