apiVersion: v1
kind: Namespace
metadata:
  name: honeycomb
spec: {}
status: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: honeycomb
  namespace: honeycomb
type: Opaque
stringData:
  # export HONEYCOMB_API_KEY env var
  api-key: $HONEYCOMB_API_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr
  namespace: honeycomb
type: kubernetes.io/dockerconfigjson
stringData:
  # export GITHUB_TOKEN env var as 'github_username:github_token'
  # export BASE64_TOKEN=$(echo -n $GITHUB_TOKEN | base64)
  .dockerconfigjson: "{\"auths\":{\"ghcr.io\":{\"auth\":\"$BASE64_TOKEN\"}}}"

## Permissions to access pod metadata
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: honeycomb-sa
  namespace: honeycomb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: honeycomb
rules:
  - apiGroups: ["", "metrics.k8s.io","apps"]
    resources: ["*"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: honeycomb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: honeycomb
subjects:
  - kind: ServiceAccount
    namespace: honeycomb
    name: honeycomb-sa
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hny-network-agent
  namespace: honeycomb
  labels:
    app: hny-network-agent
spec:
  selector:
    matchLabels:
      name: hny-network-agent
  template:
    metadata:
      labels:
        name: hny-network-agent
    spec:
      serviceAccountName: honeycomb-sa
      hostNetwork: true
      containers:
        - name: hny-network-agent
          # use locally built image from make docker-build
          image: hny/network-agent:local
          # image: ghcr.io/honeycombio/network-agent:latest
          imagePullPolicy: IfNotPresent
          # uncomment this to enable profiling listener on port 6060
          # ports:
          #   - containerPort: 6060
          env:
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: api-key
            - name: HONEYCOMB_DATASET
              value: hny-network-agent
            ## uncomment this to enable debug log level
            # - name: LOG_LEVEL
              # value: "DEBUG"
            ## uncomment this to enable profiling
            # - name: DEBUG
            #   value: "true"
          args:
            - tcp
          securityContext:
            capabilities:
              add:
                - BPF
                - PERFMON
                - NET_RAW
            # for local debugging
            # privileged: true
      imagePullSecrets:
        - name: ghcr
