apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: honeycomb-sa
  namespace: honeycomb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: honeycomb
rules:
  - apiGroups: ["", "metrics.k8s.io","apps"]
    resources: ["*"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: honeycomb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: honeycomb
subjects:
  - kind: ServiceAccount
    namespace: honeycomb
    name: honeycomb-sa
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hny-network-agent
  namespace: honeycomb
  labels:
    app: hny-network-agent
spec:
  selector:
    matchLabels:
      name: hny-network-agent
  template:
    metadata:
      labels:
        name: hny-network-agent
    spec:
      serviceAccountName: honeycomb-sa
      hostNetwork: true
      containers:
        - name: hny-network-agent
          image: ghcr.io/honeycombio/network-agent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: api-key
            - name: HONEYCOMB_DATASET
              value: hny-network-agent
            - name: HONEYCOMB_STATS_DATASET
              value: hny-network-agent-stats
          securityContext:
            capabilities:
              add:
                - NET_RAW
      imagePullSecrets:
        - name: ghcr
