apiVersion: v1
kind: Secret
metadata:
  name: ghcr
  namespace: honeycomb
type: kubernetes.io/dockerconfigjson
stringData:
  # export GITHUB_TOKEN env var as 'github_username:github_token'
  # export BASE64_TOKEN=$(echo -n $GITHUB_TOKEN | base64)
  .dockerconfigjson: "{\"auths\":{\"ghcr.io\":{\"auth\":\"$BASE64_TOKEN\"}}}"
