name: Pull Request

on:
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.5.3

      - name: Build docker image
        run: make docker-build
