name: Pull Request

on:
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.5.3

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang llvm make
          version: 1.0

      - name: build
        run: make docker-build
