name: Pull Request

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.5.3

      - name: Run tests
        run: make docker-test

      - name: Setup BATS
        uses: mig4/setup-bats@v1

      - name: Run smoke tests
        run: make smoke

      - name: Spin down smokers
        run: make unsmoke
