name: Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Install dependencies
        run: apt-get update && apt-get install -y make libpcap-dev

      - name: Run tests
        run: make test
